/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game
 * Method:    initGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Game_initGame
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBoardState
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Game_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    moveCheckerJNI
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Game_moveCheckerJNI
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Game
 * Method:    getCurrentPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWHITE_CHECKER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWHITE_1CHECKER
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBLACK_CHECKER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBLACK_1CHECKER
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWhiteScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWhiteScore
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBlackScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBlackScore
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    changeWhiteScore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeWhiteScore
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    changeBlackScore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeBlackScore
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    isEndGame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Game_isEndGame
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWinner
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getSelectedRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getSelectedRow
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getSelectedColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getSelectedColumn
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    changeSelectedRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeSelectedRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    changeSelectedColumn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeSelectedColumn
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    getClickedRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getClickedRow
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getClickedColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getClickedColumn
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    changeClickedRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeClickedRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    changeClickedColumn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeClickedColumn
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
