/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game
 * Method:    getBoardState
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Game_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    moveCheckerJNI
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Game_moveCheckerJNI
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
