/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game
 * Method:    initGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Game_initGame
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBoardCell
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Game_getBoardCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game
 * Method:    getBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getCurrentPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWHITE_CHECKER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWHITE_1CHECKER
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBLACK_CHECKER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBLACK_1CHECKER
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWhiteScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWhiteScore
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getBlackScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getBlackScore
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    changeWhiteScore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeWhiteScore
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    changeBlackScore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Game_changeBlackScore
  (JNIEnv *, jobject, jint);

/*
 * Class:     Game
 * Method:    isEndGame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Game_isEndGame
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    getWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_getWinner
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    handleCellClick
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Game_handleCellClick
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
